name: Auto-update

on:
  schedule:
    - cron: '0 8 * * 1'
  push:
    branches:
      - feature/auto-update

jobs:
  update-self:
    name: ⬇️ Updates build script
    strategy:
      matrix:
        include:
          - adapter_name: postgres
          - adapter_name: snowflake
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ checkout
        uses: actions/checkout@v3

      - name: 🏷️ Get versions
        id: versions
        run: | 
          echo "::set-output name=adapter::$(curl -s https://pypi.org/pypi/dbt-${{ matrix.adapter_name }}/json | jq -r '.info.version')"
          echo "::set-output name=elementary::$(curl -s https://pypi.org/pypi/elementary-data/json | jq -r '.info.version')"      

      - name: Update DBT-Adapter
        uses: fjogeleit/yaml-update-action@v0.13.0
        with:
          valueFile: '.github/workflows/cd.yml'
          propertyPath: "jobs['build-docker'].strategy.matrix.include[?(@.adapter_name == '${{ matrix.adapter_name }}')][0].dbt_version"
          value: ${{ steps.versions.outputs.adapter }}
          commitChange: true

      - name: Update Elementary
        uses: fjogeleit/yaml-update-action@v0.13.0
        with:
          valueFile: '.github/workflows/cd.yml'
          propertyPath: "jobs['build-docker'].strategy.matrix.include[?(@.adapter_name == '${{ matrix.adapter_name }}')][0].elementary_version"
          value: ${{ steps.versions.outputs.elementary }}
          commitChange: true

      - name: check for changes
        run: tail -n 30 .github/workflows/cd.yml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
            commit-message: ⬆️ Updated dbt-${{ matrix.adapter_name }} to ${{ steps.versions.outputs.adapter }} and elementary-data to ${{ steps.versions.outputs.elementary }}
            title: 🤖⬆️ Auto-update versions for ${{ steps.versions.outputs.adapter }}
            branch: auto-update-dependencies
